### ISSUE TITLE
Description of the pool of investors

### ISSUE THREAD

**Issue by Aporcheron** [homepaycompany/homepay_rails_monolyth#24]
**Summary:** Description of the pool of investors on the How it works page
**What is the expected correct behavior?** Property vendors should understand the kind of property investors which will purchase their properties.

**Comment by guiguiwagon** [comment]
@Aporcheron je ne vois pas les modifs, tu les as mis ou ?

**Comment by Aporcheron** [comment]
C'est la question FAQ sur la landing page.

**Comment by guiguiwagon** [comment]
@Aporcheron est ce qu'on devrait pas également mettre ça dans comment ça marche ?

**Comment by guiguiwagon** [comment]
@Aporcheron qu'est ce que tu en penses ?
