### ISSUE TITLE
Add other Frequently asked questions

### ISSUE THREAD

**Issue by Aporcheron** [homepaycompany/homepay_rails_monolyth#28]
**Summary:** Add other Frequently asked questions to support the client in the different steps of the sale process
Relevant logs and/or screenshots: https://paper.dropbox.com/doc/FAQ-M3Xw2Ouz4JZiwFbkZ41C3

**Comment by Aporcheron** [comment]
@guiguiwagon, could you please verify FAQs added on production: https://homepay-rails-monolyth-staging.herokuapp.com/faqs?

**Comment by guiguiwagon** [comment]
@Aporcheron Mes retours directement dans les screen shots
<img width="1231" alt="homepay_-_vendez_votre_logement_en_un_clic" src="https://user-images.githubusercontent.com/26580651/37779139-f2dbed72-2deb-11e8-9351-a05b04fec01a.png">
<img width="1307" alt="homepay_-_vendez_votre_logement_en_un_clic" src="https://user-images.githubusercontent.com/26580651/37779502-d8a80318-2dec-11e8-8198-4bde1e23e23b.png">
<img width="1307" alt="homepay_-_vendez_votre_logement_en_un_clic" src="https://user-images.githubusercontent.com/26580651/37779619-205a211e-2ded-11e8-9730-9644e17de773.png">
<img width="1440" alt="fullscreen_22_03_18_16_22" src="https://user-images.githubusercontent.com/26580651/37780238-a0160688-2dee-11e8-9a85-f6c2ee5fa638.png">
<img width="1440" alt="fullscreen_22_03_18_16_33" src="https://user-images.githubusercontent.com/26580651/37780325-d274fd64-2dee-11e8-8876-67d44a9e9f22.png">

**Comment by guiguiwagon** [comment]
@Aporcheron tu peux me pinguer quand tu as fini cette issue pour que je puisse la closer
