### ISSUE TITLE
Add new sentence in FAQ page

### ISSUE THREAD

**Issue by guiguiwagon** [homepaycompany/homepay_rails_monolyth#32]
Pour éviter les clients déçus, il faut préciser explicitement le type de clients vendeurs que nous visons, sans ça nous aurons certainement de nombreux clients insatisfaits et peut être de mauvaise note  (Le but n’est pas de vendre le plus possible mais de satisfaire ses utilisateurs)

Je propose d'ajouter à notre FAQ : 

**Qui peut profiter des services d'Homepay** ?
Tous nos clients souhaitent éviter les tracas d'une vente immobilière, ils veulent vendre vite et ne veulent pas passer des mois à faire des visites. Nos clients veulent vendre sans stress avec un maximum de garanties. Nous remarquons que nos clients sont souvent de jeunes couples, mutation, succession, ils viennent d'acheter plus grand et n'arrivent pas à vendre leur bien etc

**_Je te laisse le mettre à ta sauce avec tes mots_**

<img width="1126" alt="homepay_-_vendez_votre_logement_en_un_clic" src="https://user-images.githubusercontent.com/26580651/37707523-b2df554e-2d03-11e8-9d22-c7804ce11aad.png">

**Comment by guiguiwagon** [comment]
@Aporcheron est ce que tu as des questions sur cette issue ?

**Comment by Aporcheron** [comment]
J'ai ajouté le point à travers la FAQ "Dans quels cas, est-il intéressant d’utiliser les services d'Homepay ?".
