### ISSUE TITLE
Hotjar settings - delete from hotjar all localhost 3000 + heroku visites

### ISSUE THREAD

**Issue by guiguiwagon** [homepaycompany/homepay_rails_monolyth#52]
Summary: Il y a de nombreuses visites enregistrées par hotjar provenant de localhost + heroku = inutile 

What is the current operational behavior? Nombreuses visites enregistrées (localhost + heroku) sans interet 

Relevant logs and/or screenshots: 
![hotjar recordings](https://user-images.githubusercontent.com/26580651/38411132-a78e2352-3986-11e8-8e0c-f81185c97f4c.gif)

Possible fixes: Delete all this IPs

**Comment by Aporcheron** [comment]
Added cowork's ip address to Hotjar's blacklist.
